### ISSUE TITLE
Add variable length

### ISSUE THREAD

**Issue by AnalogCyan** [AnalogCyan/itadakimasu#1]
Either via a selector by the generate button, or simply always random within a range.

**Comment by mskuybeda** [comment]
Hi. May I give it a try?

**Comment by AnalogCyan** [comment]
Go ahead, you don't have to ask permission to work on issues!

**Comment by AnalogCyan** [comment]
Fixed in [extra-options](https://github.com/AnalogCyan/itadakimasu/tree/extra-options) branch.
Live branch preview visible on the [branch's subdomain](https://extra-options.itadakimasu.thayn.me/).
