### ISSUE TITLE
Expand food/drink list

### ISSUE THREAD

**Issue by AnalogCyan** [AnalogCyan/itadakimasu#2]

**Comment by brianbloom** [comment]
I'd like to take this one on,
and I also wanted to float an idea around it..

Right now you have a single "foods" array.  I am picturing splitting this into an "ingredients" array and a "dish" array.
The first is all the usual stuff: salmon, apricot, mustard
The second one extracts the types of food you might see on a menu: soup, casserole, pizza, fajita

The generator works the same but for 4 terms it picks 3 randomly from the ingredients and then appends a random "dish".
That arguably reduces a bit of the randomness combinations, but they should be more memorable and make "sense" from a recipe perspective
I also intend to add enough extra ingredients and dishes that the net entropy is at least the same if not better...

Think that's an okay idea?

**Comment by AnalogCyan** [comment]
I've actually thought about maybe doing something like this before, so feel free to go ahead with it! 

Another change along these lines that would make the recipes make more "sense" would be having any "modifier" words (steamed, fried, etc.) always show at the start if they get randomly chosen. Like you said, this would reduce the randomness a bit, but I never intended for this app to be used in any serious sense so I think that's fine.

**Comment by brianbloom** [comment]
I did the double array approach, and submitted pull request with changes for this...
