### ISSUE TITLE
Move food list to a dedicated file.

### ISSUE THREAD

**Issue by AnalogCyan** [AnalogCyan/itadakimasu#6]
Moving the food list to a dedicated text file would make it easier to manage. Ideally a simple text file with each item on its own line, imported on page load into the foods array (unless there's some other better way of doing this that's slipped my mind).

**Comment by AnalogCyan** [comment]
Previous fix broke PWA functionality, looking into how to fix that...

**Comment by brianbloom** [comment]
I can understand the point of wanting the data in another file, but what is the motivation for wanting a plain text file (as opposed to a JS structure?

Right now, with it instantiated already as an array, there is no performance cost with having to parse and import the data - it's already ready to consume as soon as the file is loaded. Extracting the data into a flatfile with simple text will add to the load and processing time for the app.

**Comment by astriskit** [comment]
I think, it is a nice idea; And I suggest using `.json` format for doing so. But I'm wondering, what is it that you faced earlier, when you tried to do it; Would you share some information on that, @AnalogCyan
Also, if you are ok with the idea, I may try to implement it using the `.json`.

**Comment by AnalogCyan** [comment]
I'm honestly not quite sure what the issue was, but if I had to guess it's likely something to do with how I've configured the PWA functionality, as for some reason the file was not becoming available offline with the rest of the app when installed.
But yeah, feel free to take a shot at it @astriskit
